---
# playbooks/docker-cleanup.yml
- name: Cleanup Docker installation attempts
  hosts: docker
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Remove Docker repository file
      file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent
        
    - name: Remove downloaded GPG key from tmp
      file:
        path: /tmp/docker-archive-keyring.gpg
        state: absent
        
    - name: Remove GPG key from keyrings
      file:
        path: /etc/apt/keyrings/docker-archive-keyring.gpg
        state: absent
        
    - name: Update package cache
      apt:
        update_cache: yes
        
    - name: Display cleanup status
      debug:
        msg: "Docker repository and keys cleaned up successfully"
