---
# playbooks/system-update.yml
- name: Update all systems
  hosts: all
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Update apt packages (Ubuntu/Debian)
      apt:
        update_cache: yes
        upgrade: yes
      when: ansible_os_family == "Debian"
      register: apt_update_result
      
    - name: Display apt update results
      debug:
        msg: "APT update completed on {{ inventory_hostname }}"
      when: apt_update_result is defined and apt_update_result.changed
    - name: Update Homebrew packages
      shell: |
        export PATH="/home/linuxbrew/.linuxbrew/bin:/opt/homebrew/bin:/usr/local/bin:$PATH"
        brew update && brew upgrade
      become: no
      register: brew_update_result
      failed_when: false  # Ignore failures (e.g., if brew not installed)
      changed_when: "'Already up-to-date' not in brew_update_result.stdout"
    - name: Display Homebrew update results
      debug:
        msg: "Homebrew update completed on {{ inventory_hostname }}"
      when: brew_update_result is defined and brew_update_result.rc == 0
