---
all:
  children:
    docker:
      hosts:
        docker-host:
          ansible_host: 192.168.2.171
          ansible_user: albaz
    kubernetes:
      children:
        k8s_masters:
          hosts:
            # k8s-master-01:
            #   ansible_host: IP_ADDRESS
            #   ansible_user: YOUR_USERNAME
        k8s_workers:
          hosts:
            # k8s-worker-01:
            #   ansible_host: IP_ADDRESS
            #   ansible_user: YOUR_USERNAME
            # k8s-worker-02:
            #   ansible_host: IP_ADDRESS
            #   ansible_user: YOUR_USERNAME
